use_ransac: false

# common
min_radius: 0.05
max_radius: 0.10
do_refine: true

x_filter_min: -0.4
x_filter_max: 0.4

z_filter_min: 0.4
z_filter_max: 1.0

# hough
angle_bins: 30
radius_bins: 10
position_bins: 20
mode: 2
accumulator_peak_threshold: 0.5
gaussian_sphere_points_num: 500
orientation_accumulators_num: 10

orientation_hough_gmm:
  -
    id: 1
    weight: 0.5
    mean: [0.0, 0.0,1.0]
    standard_deviation: [0.05,0.05,0.05]
  -
    id: 2
    weight: 0.5
    mean: [0.0,0.0,0.0]
    standard_deviation: [1.0,1.0,0.005]

# ransac
normal_distance_weight: 0.1
max_iterations: 10000
distance_threshold: 0.02
cluster_tolerance: 0.02
min_cluster_size: 200
max_cluster_size: 8000
table_z_filter_min: 0.01
table_z_filter_max: 0.4
plane_detection_voxel_size: 0.05
cluster_voxel_size: 0.005
inlier_threshold: 10

# voxel grid
filter_field_name: z
filter_limit_min: 0.015
filter_limit_max: 3.0
filter_limit_negative: False
leaf_size: 0.03
camera_info_topic: /kinect2/hd/camera_info

# CLASSIFIER PARAMS
classifier_absolute_path_folder: /home/rui/ws/src/shape_detection_fitting
model_file: /lib/shape-classification/base_networks/squeezenet/deploy.prototxt
weight_file: /lib/shape-classification/base_networks/squeezenet/squeezenet_v1.1.caffemodel
mean_file: /lib/shape-classification/dataset/mean.binaryproto

device: GPU
device_id: 1
classification_threshold: 0.5
fitting_distance_threshold: 0.02
fitting_acceptance_threshold: 0.5
padding: 0.0

with_classifier: false
visualize: false


# KINECT V1
#camera_matrix: [-1.0607072507083330e+03,0.,9.5635447181548398e+02,0.,1.0586083263054650e+03,5.3997844298824486e+02,0.,0.,1.]
#rotation: [9.9999932279092762e-01,1.1418659978192800e-03,-2.2485490683788145e-04,-1.1422648685177200e-03,9.9999776014165309e-01,-1.7818368744440499e-03,2.2281978425420061e-04, 1.7820925116285419e-03, 9.9999838724751144e-01]
#translation: [-7.1227840324258434e-02,-7.5307585220976776e-04,7.0571985343338605e-05]

# ASUS XTION
camera_matrix: [570.3422241210938,0.0,314.5,0.0,570.3422241210938,235.5,0.0,0.0,1.0]
rotation: [1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0]
translation: [-0.025,0.0,0.0]





