use_ransac: false

# common
min_radius: 0.03
max_radius: 0.09

# hough
gaussian_sphere_points_num: 600
angle_bins: 30
radius_bins: 10
position_bins: 20

# ransac
normal_distance_weight: 0.1
max_iterations: 10000
distance_threshold: 0.05


# voxel grid
filter_field_name: z
filter_limit_min: 0.01
filter_limit_max: 1.5
filter_limit_negative: False
leaf_size: 0.03


camera_info_topic: /camera/rgb/camera_info
