use_ransac: false

# common
min_radius: 0.03
max_radius: 0.08
do_refine: true

x_filter_min: -0.4
x_filter_max: 0.4

z_filter_min: 0.4
z_filter_max: 1.0

# hough cylinder fitting
angle_bins: 30
radius_bins: 10
position_bins: 20
hough_fitting_mode: 2 # normal - 0, hybrid - 2
accumulator_peak_threshold: 0.5
gaussian_sphere_points_num: 1000
orientation_accumulators_num: 30

orientation_hough_gmm:
  -
    id: 1
    weight: 0.33
    mean: [0.0, 0.0,1.0]
    standard_deviation: [0.005,0.005,0.005]
  -
    id: 2
    weight: 0.33
    mean: [0.0,0.0,0.0]
    standard_deviation: [0.05,0.05,0.005]
  -
    id: 3
    weight: 0.33
    mean: [0.0,0.0,0.0]
    standard_deviation: [0.05,0.05,0.05]
  

# ransac plane fitting
normal_distance_weight: 0.3
max_iterations: 10000
distance_threshold: 0.02
cluster_tolerance: 0.02
min_cluster_size: 100
max_cluster_size: 2000
table_z_filter_min: 0.03
table_z_filter_max: 0.4
plane_detection_voxel_size: 0.05
cluster_voxel_size: 0.005
inlier_threshold: 10

# voxel grid
filter_field_name: z
filter_limit_min: 0.5
filter_limit_max: 1.0

# classifier
classifier_absolute_path_folder: /home/rui/ws/src/shape_detection_fitting
model_file: /lib/shape-classification/base_networks/squeezenet/deploy.prototxt
weight_file: /lib/shape-classification/base_networks/squeezenet/squeezenet_v1.1.caffemodel
mean_file: /lib/shape-classification/dataset/mean.binaryproto

device: GPU
device_id: 0
classification_threshold: 0.5
fitting_distance_threshold: 0.02
padding: 0.1

with_classifier: true
visualize: false
visualize_ground_truth: true

# acquire dataset
dataset_create: false
dataset_path: /home/rui/dataset
object_type: cylinder
## CAMERA PARAMS

# KINECT V1
#camera_matrix: [-1.0607072507083330e+03,0.,9.5635447181548398e+02,0.,1.0586083263054650e+03,5.3997844298824486e+02,0.,0.,1.]
#rotation: [9.9999932279092762e-01,1.1418659978192800e-03,-2.2485490683788145e-04,-1.1422648685177200e-03,9.9999776014165309e-01,-1.7818368744440499e-03,2.2281978425420061e-04, 1.7820925116285419e-03, 9.9999838724751144e-01]
#translation: [-7.1227840324258434e-02,-7.5307585220976776e-04,7.0571985343338605e-05]

# ASUS XTION
camera_matrix: [570.3422241210938,0.0,314.5,0.0,570.3422241210938,235.5,0.0,0.0,1.0]
rotation: [1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0]
translation: [-0.025,0.0,0.0]





