# common
min_radius: 0.05
max_radius: 0.3

# hough
gaussian_sphere_points_num: 600
angle_bins: 30
radius_bins: 10
position_bins: 20

# ransac
normal_distance_weight: 0.1
max_iterations: 100
distance_threshold: 0.01
